---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: awx-admin-password
  namespace: awx
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: awx-admin-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: k3s-sno/awx/admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: awx-postgres-configuration
  namespace: awx
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: awx-postgres-configuration
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: awx-db-rw.cnpg-system.svc
        port: "5432"
        database: awx
        username: awx
        password: "{{ .password }}"
        type: unmanaged
  data:
    - secretKey: password
      remoteRef:
        key: k3s-sno/awx/postgres-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: awx-secret-key
  namespace: awx
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: awx-secret-key
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: k3s-sno/awx/secret-key
