---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: operator-oauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: "{{ .clientId }}"
        client_secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientId
      remoteRef:
        key: k3s-sno/tailscale/oauth-client-id
    - secretKey: clientSecret
      remoteRef:
        key: k3s-sno/tailscale/oauth-client-secret
