---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: squest-secret-key
  namespace: squest
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: squest-secret-key
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: k3s-sno/squest/secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: squest-db-password
  namespace: squest
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: squest-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: k3s-sno/squest/db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: squest-rabbitmq-password
  namespace: squest
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: squest-rabbitmq-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: k3s-sno/squest/rabbitmq-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: squest-redis-password
  namespace: squest
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: squest-redis-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: k3s-sno/squest/redis-password
