---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - configmap.yaml
  - nginx-config.yaml
  - pvc.yaml
  - redis.yaml
  - rabbitmq.yaml
  - deployment.yaml
  - service.yaml
